Repository nbclastprojec/ShareDream, pull requests merged in 2023-10, with the labels that each got.

#2 UI/ loginpage,homepage | fix/ gradle
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12__12_55__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12__1_03__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12__1_03__Changes_1.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12_오후_12_55_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12_오후_1_03_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12_오후_1_03_[Changes]1/shelved.patch
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/dreamteam/sharedream/Fragment_alarm.kt
  app/src/main/java/com/dreamteam/sharedream/Fragment_edit.kt
  app/src/main/java/com/dreamteam/sharedream/Fragment_home.kt
  app/src/main/java/com/dreamteam/sharedream/Fragment_login.kt
  app/src/main/java/com/dreamteam/sharedream/Fragment_login_main.kt
  app/src/main/java/com/dreamteam/sharedream/Fragment_signup.kt
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/ViewPagerAdapter.kt
  app/src/main/res/drawable/agreeboxline.xml
  app/src/main/res/drawable/arrow.png
  app/src/main/res/drawable/btn_camera.xml
  app/src/main/res/drawable/btn_google.xml
  app/src/main/res/drawable/btn_home.png
  app/src/main/res/drawable/btn_search.png
  app/src/main/res/drawable/camera.png
  app/src/main/res/drawable/checkboxline.xml
  app/src/main/res/drawable/edit_searchbox.xml
  app/src/main/res/drawable/google.png
  app/src/main/res/drawable/login_editbox.xml
  app/src/main/res/drawable/loginbox_first.xml
  app/src/main/res/drawable/loginbtn.xml
  app/src/main/res/drawable/loginbtn_2.xml
  app/src/main/res/drawable/trade.png
  app/src/main/res/drawable/xx.png
  app/src/main/res/font/bmdh.ttf
  app/src/main/res/font/bmhannaair.ttf
  app/src/main/res/font/bmhannapro.ttf
  app/src/main/res/font/font_familly.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_edit.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_login_main.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/myalarm.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug, UI

#3 [UI] ChattingRoom Page / Chat Page UI
  app/build.gradle.kts
  app/src/main/res/drawable/example.png
  app/src/main/res/layout/chattingroom_item.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_detailpage.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_profile.xml
Labels: UI

#4 [DESIGN] 전반적인 UI 추가/수정
  app/build.gradle.kts
  app/src/main/res/layout/fragment_mypage_profile.xml
  app/src/main/res/layout/like_item.xml
  app/src/main/res/layout/trade_item.xml
  app/src/main/res/layout/write_item.xml
Labels: UI

#7 Fix/log in pg
  app/build.gradle.kts
  app/src/main/java/com/dreamteam/sharedream/LoginFragment.kt
  app/src/main/java/com/dreamteam/sharedream/SignUpFragment.kt
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_signup.xml
Labels: enhancement

#9 Feat/ home page
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dreamteam/sharedream/EditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/LogInMainFragment.kt
  app/src/main/java/com/dreamteam/sharedream/LoginFragment.kt
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/ViewPagerAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostData.kt
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Feature

#10 Feat/home page image download
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12__12_55__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12__1_03__Changes_1.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12_오후_12_55_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12_오후_1_03_[Changes]1/shelved.patch
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditImageAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostData.kt
  app/src/main/res/drawable/circle_x.png
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/edit_image_item.xml
Labels: Feature

#13 Feat/home page image download
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/CategoryDialogFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditImageAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostData.kt
  app/src/main/res/drawable/chip_circle.xml
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/fragment_category_dialog.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/themes.xml
Labels: bug, Feature

#17 Feature/search pg
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachFragment.kt
  app/src/main/res/drawable/edit_searchbox.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_seach.xml
Labels: Feature

#18 Feat/mypage/profile/edit
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/SignUpFragment.kt
  app/src/main/java/com/dreamteam/sharedream/Util/Util.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostData.kt
  app/src/main/java/com/dreamteam/sharedream/model/UserData.kt
  app/src/main/java/com/dreamteam/sharedream/view/MyPostFeedFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MyPostFeedViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/view/MypageEditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MypageFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/DifferCallback.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/MyPostFeedAdapter.kt
  app/src/main/res/drawable/ic_delete_account.png
  app/src/main/res/drawable/profile_circle.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_inquiry.xml
  app/src/main/res/layout/fragment_login_main.xml
  app/src/main/res/layout/fragment_my_post_feed.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_edit_profile.xml
  app/src/main/res/values/arrays.xml
Labels: Feature, Fix

#19 Feature/구글 로그인시 추가정보 입력창 추가
  .idea/deploymentTargetDropDown.xml
  app/google-services.json
  app/src/main/java/com/dreamteam/sharedream/DetailPageFragment.kt
  app/src/main/java/com/dreamteam/sharedream/InputUserData.kt
  app/src/main/java/com/dreamteam/sharedream/LogInActivity.kt
  app/src/main/java/com/dreamteam/sharedream/LogInMainFragment.kt
  app/src/main/res/layout/fragment_agree.xml
  app/src/main/res/layout/fragment_input_user_data.xml
  app/src/main/res/layout/fragment_personal_agree.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#21 Feature/alarm pg/fcm
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dreamteam/sharedream/FCMService.kt
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/CategoryDialogFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachFragment.kt
  app/src/main/java/com/dreamteam/sharedream/model/Post.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostData.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/res/drawable/btn_floating.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_seach.xml
  app/src/main/res/layout/write_item.xml
Labels: documentation, Fix

#26 Feat/detail state change
  app/src/main/java/com/dreamteam/sharedream/SignUpFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/model/UserData.kt
  app/src/main/java/com/dreamteam/sharedream/view/MyPostFeedFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MypageEditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MypageFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/layout/fragment_my_post_feed_detail.xml
  app/src/main/res/layout/fragment_mypage_edit_profile.xml
  app/src/main/res/layout/fragment_post_detail.xml
Labels: Feature, Fix

#28 Feat/detail fix
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostEditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/DifferCallback.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/drawable/bg_img_completed_trade.png
  app/src/main/res/drawable/bg_img_completed_trade2.png
  app/src/main/res/drawable/bg_img_completed_trade3.png
  app/src/main/res/drawable/bg_state_img_closed_white.png
  app/src/main/res/drawable/bg_state_img_put_off_white.png
  app/src/main/res/drawable/bg_state_img_reservation_white.png
  app/src/main/res/layout/fragment_post_detail.xml
  app/src/main/res/layout/fragment_post_edit.xml
  app/src/main/res/layout/write_item.xml
Labels: Feature, Fix
