Repository nbclastprojec/ShareDream, pull requests merged in 2023-11, with the labels that each got.

#31 Feat/search pg&&sort
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/CategoryDialogFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditImageAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SearchRepository.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SearchViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmPostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/model/Post.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostRcv.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostEditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/MyPostFeedAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/fragment_category_dialog.xml
  app/src/main/res/layout/fragment_find_email_dialog.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_seach.xml
  app/src/main/res/layout/spinner_item.xml
  app/src/main/res/values/arrays.xml
Labels: Feature, Fix

#32 [FIX] categoryPG MVVM리팩토링, priceFilter 수정
  app/build.gradle.kts
  app/src/main/java/com/dreamteam/sharedream/home/CategoryDialogFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/CategoryViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeRepository.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SearchViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostRcv.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/drawable/ic_backbtn.png
  app/src/main/res/layout/fragment_category_dialog.xml
Labels: Fix

#33 [Design] 전체적인 icon 수정 및 layout 수정
  app/src/main/res/drawable/clamp.png
  app/src/main/res/drawable/ic_image.png
  app/src/main/res/drawable/icn_bookmark.png
  app/src/main/res/drawable/icn_bookmark_list.png
  app/src/main/res/drawable/icn_chat_list.png
  app/src/main/res/drawable/icn_mypost_list.png
  app/src/main/res/drawable/icn_mytrade_list.png
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/fragment_category_dialog.xml
  app/src/main/res/layout/fragment_chattingroom.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_inquiry.xml
  app/src/main/res/layout/fragment_likepage.xml
  app/src/main/res/layout/fragment_my_post_feed.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_edit_profile.xml
  app/src/main/res/layout/fragment_post_detail.xml
  app/src/main/res/layout/fragment_post_edit.xml
  app/src/main/res/layout/fragment_seach.xml
  app/src/main/res/layout/fragment_tradepage.xml
  app/src/main/res/layout/trade_item.xml
  app/src/main/res/values/colors.xml
Labels: UI

#34 [Feat] location picker
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dreamteam/sharedream/Util/Util.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeRepository.kt
  app/src/main/java/com/dreamteam/sharedream/model/LocationData.kt
  app/src/main/java/com/dreamteam/sharedream/model/Post.kt
  app/src/main/java/com/dreamteam/sharedream/model/PostRcv.kt
  app/src/main/java/com/dreamteam/sharedream/view/MapViewFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostEditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/drawable/map_ic_marker_fill_red32.png
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/fragment_login_main.xml
  app/src/main/res/layout/fragment_map_view.xml
  app/src/main/res/layout/fragment_post_detail.xml
  app/src/main/res/layout/fragment_post_edit.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  settings.gradle.kts
Labels: Feature, Fix

#39 [Feat] FCM Notification
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dreamteam/sharedream/FCMService.kt
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/Util/Constants.kt
  app/src/main/java/com/dreamteam/sharedream/Util/FCMInterface.kt
  app/src/main/java/com/dreamteam/sharedream/Util/FcmRetrofitInstance.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeRepository.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmFragment.kt
  app/src/main/java/com/dreamteam/sharedream/model/MessageDTO.kt
  app/src/main/java/com/dreamteam/sharedream/model/NotificationBody.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  functions/sharedream-7c146-firebase-adminsdk-bhclr-9cf8634f5d.json
Labels: Feature

#41 [Feat] Chatting PG delete 기능
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/dreamteam/sharedream/chat/ChatFragment.kt
  app/src/main/java/com/dreamteam/sharedream/chat/ChatMessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/chat/MessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/res/drawable/chatting_me.xml
  app/src/main/res/drawable/ic_chat_dot.png
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/chat_dialog.xml
  app/src/main/res/layout/chattingroom_item.xml
Labels: Feature

#42 [Feat]alarm pg recieve,delete 기능 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/dreamteam/sharedream/FCMService.kt
  app/src/main/java/com/dreamteam/sharedream/Util/Constants.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmPostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmRepo.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/model/AlarmPost.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/drawable/trashcan.png
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/myalarm.xml
Labels: Feature

#45 UI/home pg dialog
  app/src/main/java/com/dreamteam/sharedream/home/CategoryDialogFragment.kt
  app/src/main/res/color/chip_bg_state_color.xml
  app/src/main/res/color/chip_text_state_color.xml
  app/src/main/res/drawable/button4.xml
  app/src/main/res/drawable/catecomplebtn_drawble.xml
  app/src/main/res/drawable/chip_circle.xml
  app/src/main/res/drawable/leftbubble_1.png
  app/src/main/res/drawable/leftbubble_2.png
  app/src/main/res/drawable/leftbubble_3.png
  app/src/main/res/drawable/leftbubble_4.png
  app/src/main/res/drawable/rightbubble_1.png
  app/src/main/res/drawable/rightbubble_2.png
  app/src/main/res/drawable/rightbubble_3.png
  app/src/main/res/drawable/rightbubble_4.png
  app/src/main/res/layout/fragment_category_dialog.xml
  app/src/main/res/layout/write_item.xml
  app/src/main/res/values/styles.xml
Labels: UI

#46 스플래시 파일 test
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dreamteam/sharedream/splash.kt
  app/src/main/res/anim/animation.xml
  app/src/main/res/anim/animation2.xml
  app/src/main/res/drawable/animation.gif
  app/src/main/res/layout/activity_splash.xml
Labels: Feature

#47 [Feat] Splash 페이지 추가 및 로그인 기능 xml 비율 수정
  app/src/main/java/com/dreamteam/sharedream/FindEmailWithIdFragment.kt
  app/src/main/java/com/dreamteam/sharedream/LoginFragment.kt
  app/src/main/java/com/dreamteam/sharedream/SendPasswordFragment.kt
  app/src/main/java/com/dreamteam/sharedream/SignUpFragment.kt
  app/src/main/java/com/dreamteam/sharedream/splash.kt
  app/src/main/java/com/dreamteam/sharedream/view/MapViewFragment.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_agree.xml
  app/src/main/res/layout/fragment_calender_dialog.xml
  app/src/main/res/layout/fragment_edit_calender_dialog.xml
  app/src/main/res/layout/fragment_find_email_dialog.xml
  app/src/main/res/layout/fragment_find_email_with_id.xml
  app/src/main/res/layout/fragment_input_user_data.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_login_main.xml
  app/src/main/res/layout/fragment_nickname_check_dailalog.xml
  app/src/main/res/layout/fragment_password_check_dialog.xml
  app/src/main/res/layout/fragment_personal_agree.xml
  app/src/main/res/layout/fragment_send_password.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/fragment_your_detail_page.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#48 [Ui / Feat ] chatting pg
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dreamteam/sharedream/chat/ChatMessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/chat/MessageActivity.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/chat_dialog.xml
  app/src/main/res/layout/chat_item.xml
  app/src/main/res/layout/chattingroom_item.xml
  app/src/main/res/layout/fragment_chattingroom.xml
  app/src/main/res/layout/fragment_inquiry.xml
Labels: Feature, UI

#49 [UI]search pg
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/Util/Constants.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeRepository.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SearchRepository.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmRepo.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_seach.xml
  app/src/main/res/values/styles.xml
Labels: UI

#50 [Ui] Chat PG / Dialog
  app/src/main/java/com/dreamteam/sharedream/chat/ChatMessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/chat/MessageActivity.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/chat_item.xml
  app/src/main/res/layout/chattingroom_item.xml
  app/src/main/res/layout/fragment_edit_calender_dialog.xml
  app/src/main/res/layout/fragment_find_email_with_id.xml
  app/src/main/res/layout/fragment_nickname_check_dailalog.xml
  app/src/main/res/layout/fragment_send_password.xml
Labels: UI

#53 [UI]launch test_writePG,homePG,otheProfile,Detail,myPG수정
  app/src/main/java/com/dreamteam/sharedream/FCMService.kt
  app/src/main/java/com/dreamteam/sharedream/SignUpFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmPostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostEditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/fragment_category_dialog.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_edit_profile.xml
  app/src/main/res/layout/fragment_post_edit.xml
  app/src/main/res/layout/fragment_your_detail_page.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: UI

#54 Hotfix/error
  app/src/main/java/com/dreamteam/sharedream/Util/Util.kt
  app/src/main/java/com/dreamteam/sharedream/home/Edit/EditFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MapViewFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MypageFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostEditFragment.kt
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/write_item.xml
Labels: bug, Feature, Fix

#56 [Feat] 회원탈퇴 및 삭제시 데이터제거 기능/xml 오류 fix
  app/build.gradle.kts
  app/src/main/java/com/dreamteam/sharedream/SignUpFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MypageFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/YourDetailRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_nickname_check_dailalog.xml
  app/src/main/res/layout/fragment_your_detail_page.xml
  app/src/main/res/layout/fragment_your_detail_recycler_view.xml
Labels: Feature

#57 [Feat] Chatting Image 전송
  app/src/main/java/com/dreamteam/sharedream/chat/ChatMessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/chat/ChatModel.kt
  app/src/main/java/com/dreamteam/sharedream/chat/MessageActivity.kt
  app/src/main/res/drawable/chat_other.xml
  app/src/main/res/drawable/chatmine.xml
  app/src/main/res/drawable/chatother.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/chat_item.xml
Labels: Feature, UI

#58 [Feat]종료 다이얼로그 설정, xml수정 ,유효성검사 수정
  app/google-services.json
  app/src/main/java/com/dreamteam/sharedream/LogInActivity.kt
  app/src/main/java/com/dreamteam/sharedream/LogInMainFragment.kt
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/splash.kt
  app/src/main/res/layout/activity_chat.xml
Labels: Feature

#59 Fix/2nd qa
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/dreamteam/sharedream/home/HomeFragment.kt
  app/src/main/java/com/dreamteam/sharedream/model/InquiryData.kt
  app/src/main/java/com/dreamteam/sharedream/splash.kt
  app/src/main/java/com/dreamteam/sharedream/view/InquiryFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/MypageFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/HomePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/MyPageFavoritePostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/view/adapter/MyPostFeedAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/DetailPost/DetailPostViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/HomePost/HomePostViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/ImgRepository.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/ImgRepositoryImpl.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/Inquiry/InquiryRepository.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/Inquiry/InquiryRepositoryImpl.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/Inquiry/InquiryViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/Inquiry/InquiryViewModelFactory.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/MyPostFeedViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/PostRepository.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/PostRepositoryImpl.kt
  app/src/main/java/com/dreamteam/sharedream/viewmodel/PostViewModelFactory.kt
  app/src/main/res/layout/fragment_inquiry.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/arrays.xml
Labels: Feature, Fix

#61 Fix/location keyword
  app/src/main/java/com/dreamteam/sharedream/Util/Util.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SeachFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SearchRepository.kt
  app/src/main/java/com/dreamteam/sharedream/home/Search/SearchViewModel.kt
  app/src/main/java/com/dreamteam/sharedream/view/MapViewFragment.kt
Labels: Feature, Fix

#62 [Fix] Chatting image 전송 기능
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/dreamteam/sharedream/chat/ChatMessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/chat/MessageActivity.kt
Labels: Fix

#64 [Feat] 닉네임 입력 다이얼로그 Cancelable 불가 추가
  app/src/main/java/com/dreamteam/sharedream/NicknameCheckDailogFragment.kt
Labels: Feature

#65 [Feat] notiPG feature
  app/src/main/java/com/dreamteam/sharedream/chat/ChatMessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/chat/MessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/home/HomeRepository.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmAdapter2.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmPostAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/model/AlarmChatData.kt
  app/src/main/java/com/dreamteam/sharedream/view/PostDetailFragment.kt
  app/src/main/res/drawable/like.png
  app/src/main/res/layout/fragment_seach.xml
  app/src/main/res/layout/myalarm.xml
Labels: Feature

#66 UI/ overall(1)
  app/src/main/java/com/dreamteam/sharedream/MainActivity.kt
  app/src/main/java/com/dreamteam/sharedream/ViewPagerAdapter.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmFragment.kt
  app/src/main/java/com/dreamteam/sharedream/home/alarm/AlarmPostAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_edit_calender_dialog.xml
  app/src/main/res/layout/myalarm.xml
  app/src/main/res/values/styles.xml
Labels: Fix

#69 [Ui] 전체 이미지 UI 수정
  app/src/main/java/com/dreamteam/sharedream/chat/ChatMessageActivity.kt
  app/src/main/java/com/dreamteam/sharedream/chat/MessageActivity.kt
  app/src/main/res/layout/activity_edit.xml
  app/src/main/res/layout/chat_dialog.xml
  app/src/main/res/layout/chat_item.xml
  app/src/main/res/layout/fragment_category_dialog.xml
  app/src/main/res/layout/fragment_find_email_dialog.xml
  app/src/main/res/layout/fragment_input_user_data.xml
  app/src/main/res/layout/fragment_inquiry.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/write_item.xml
Labels: UI

#70 [UI] filter, detail, notify PG design fix
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_category_dialog.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_post_detail.xml
  app/src/main/res/layout/myalarm.xml
  app/src/main/res/values/styles.xml
Labels: UI

#71 [Fix]아이디 찾기 오류 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/dreamteam/sharedream/EmailPasswordDialogFragment.kt
  app/src/main/res/layout/fragment_nickname_check_dailalog.xml
Labels: bug
